// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package client

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"

	types "go.osspkg.com/goppy/v3/_example/web-server-gen/types"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient(in *jlexer.Lexer, out *UserNameV1Response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient(out *jwriter.Writer, in UserNameV1Response) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserNameV1Response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserNameV1Response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserNameV1Response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserNameV1Response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient(l, v)
}
func easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient1(in *jlexer.Lexer, out *UserNameV1Request) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient1(out *jwriter.Writer, in UserNameV1Request) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserNameV1Request) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserNameV1Request) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserNameV1Request) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserNameV1Request) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient1(l, v)
}
func easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient2(in *jlexer.Lexer, out *PostListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
				out.Text = nil
			} else {
				in.Delim('[')
				if out.Text == nil {
					if !in.IsDelim(']') {
						out.Text = make([]types.Text, 0, 2)
					} else {
						out.Text = []types.Text{}
					}
				} else {
					out.Text = (out.Text)[:0]
				}
				for !in.IsDelim(']') {
					var v1 types.Text
					easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenTypes(in, &v1)
					out.Text = append(out.Text, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient2(out *jwriter.Writer, in PostListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Text) != 0 {
		const prefix string = ",\"text\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v2, v3 := range in.Text {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenTypes(out, v3)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient2(l, v)
}
func easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenTypes(in *jlexer.Lexer, out *types.Text) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "Text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenTypes(out *jwriter.Writer, in types.Text) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"Text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	out.RawByte('}')
}
func easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient3(in *jlexer.Lexer, out *PostListRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient3(out *jwriter.Writer, in PostListRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostListRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostListRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostListRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostListRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient3(l, v)
}
func easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient4(in *jlexer.Lexer, out *PostByIDResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient4(out *jwriter.Writer, in PostByIDResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Text))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostByIDResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostByIDResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostByIDResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostByIDResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient4(l, v)
}
func easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient5(in *jlexer.Lexer, out *PostByIDRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient5(out *jwriter.Writer, in PostByIDRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostByIDRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostByIDRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostByIDRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostByIDRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient5(l, v)
}
func easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient6(in *jlexer.Lexer, out *ApiRootV1Response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient6(out *jwriter.Writer, in ApiRootV1Response) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ApiRootV1Response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ApiRootV1Response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ApiRootV1Response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ApiRootV1Response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient6(l, v)
}
func easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient7(in *jlexer.Lexer, out *ApiRootV1Request) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient7(out *jwriter.Writer, in ApiRootV1Request) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userName\":"
		out.RawString(prefix[1:])
		out.String(string(in.UserName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ApiRootV1Request) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ApiRootV1Request) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ApiRootV1Request) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ApiRootV1Request) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient7(l, v)
}
func easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient8(in *jlexer.Lexer, out *ApiAuthV1Response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient8(out *jwriter.Writer, in ApiAuthV1Response) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ApiAuthV1Response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ApiAuthV1Response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ApiAuthV1Response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ApiAuthV1Response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient8(l, v)
}
func easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient9(in *jlexer.Lexer, out *ApiAuthV1Request) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient9(out *jwriter.Writer, in ApiAuthV1Request) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userName\":"
		out.RawString(prefix[1:])
		out.String(string(in.UserName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ApiAuthV1Request) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ApiAuthV1Request) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93e197c5EncodeGoOsspkgComGoppyV3ExampleWebServerGenClient9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ApiAuthV1Request) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ApiAuthV1Request) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93e197c5DecodeGoOsspkgComGoppyV3ExampleWebServerGenClient9(l, v)
}
