/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

// Code generated by goppy-cli tb. DO NOT EDIT.
package client

import (
	context "context"

	jsonrpc "go.osspkg.com/goppy/v3/web/jsonrpc"
)

type UserClient struct {
	cli *jsonrpc.Client
}

func NewUserClient(address string, opts ...jsonrpc.Opt) *UserClient {
	return &UserClient{
		cli: jsonrpc.New(address, opts...),
	}
}

func (v *UserClient) CallNameV1(ctx context.Context, req UserNameV1Request) (res UserNameV1Response, err error) {
	err = v.cli.Call(ctx, req.Method(), req, &res)
	return
}
