/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

// Code generated by goppy-cli tb. DO NOT EDIT.
package client

//go:generate easyjson
import types "go.osspkg.com/goppy/v3/examples/internal/web-server-gen/types"

//easyjson:json
type ApiRootV1Request struct {
	UserName string `json:"userName"`
}

func (ApiRootV1Request) Method() string {
	return "api.rootv1"
}

//easyjson:json
type ApiRootV1Response struct {
	Status bool `json:"status"`
}

//easyjson:json
type ApiAuthV1Request struct {
	UserName string `json:"userName"`
}

func (ApiAuthV1Request) Method() string {
	return "api.authv1"
}

//easyjson:json
type ApiAuthV1Response struct{}

//easyjson:json
type UserNameV1Request struct {
	UserID int64 `json:"userID"`
}

func (UserNameV1Request) Method() string {
	return "user.namev1"
}

//easyjson:json
type UserNameV1Response struct {
	Name string `json:"name"`
}

//easyjson:json
type PostByIDRequest struct {
	ID int64 `json:"ID"`
}

func (PostByIDRequest) Method() string {
	return "post.byid"
}

//easyjson:json
type PostByIDResponse struct {
	Text bool `json:"text"`
}

//easyjson:json
type PostListRequest struct {
	UserID int64 `json:"userID"`
}

func (PostListRequest) Method() string {
	return "post.list"
}

//easyjson:json
type PostListResponse struct {
	Text []types.Text `json:"text,omitempty"`
}
