/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"go.osspkg.com/ioutils/fs"

	"go.osspkg.com/goppy/v3/pkg/assets"
	"go.osspkg.com/goppy/v3/pkg/console"
)

var (
	validRex = regexp.MustCompile(`(?i)[^a-z0-9]`)
	packRex  = regexp.MustCompile(`package ([a-z0-9_]+)`)
)

func CmdAssetsBuild() console.CommandGetter {
	return console.NewCommand(func(setter console.CommandSetter) {
		setter.Setup("assets", "Generate assets to go file")
		setter.Flag(func(flagsSetter console.FlagsSetter) {
			flagsSetter.StringVar("src", ".", "source folder")
			flagsSetter.StringVar("func", "getAssets", "func name for getting assets reader")
		})
		setter.ExecFunc(func(src, name string) {
			if !fs.FileExist(src) {
				console.Fatalf("`%s` does not exist", src)
			}

			curr := fs.CurrentDir()

			pkg, err := getPackageFromFirstFile(curr)
			if err != nil {
				pkg = strings.ToLower(filepath.Base(curr))
			}

			pkg = validRex.ReplaceAllString(pkg, `_`)
			name = validRex.ReplaceAllString(name, `_`)

			sf := assets.New()
			console.FatalIfErr(sf.FromDir(filepath.Join(curr, src)), "failed to generate assets")

			fi, err := os.Create(filepath.Join(curr, strings.ToLower(name)+assets.FileSuffix))
			console.FatalIfErr(err, "failed create file")
			defer fi.Close() //nolint:errcheck

			fmt.Fprintf(fi, "// Code generated by goppy assets. DO NOT EDIT.\n\n") //nolint:errcheck
			fmt.Fprintf(fi, "package %s\n\n", pkg)                                 //nolint:errcheck
			fmt.Fprintf(fi, "import \"go.osspkg.com/goppy/v3/pkg/assets\"\n\n")    //nolint:errcheck
			fmt.Fprintf(fi, "const __%s = \"", name)                               //nolint:errcheck
			console.WarnIfErr(sf.ToBase64TGZ(fi), "failed to write assets as base64")
			fmt.Fprintf(fi, "\"\n\n")                                                  //nolint:errcheck
			fmt.Fprintf(fi, "func %s() (assets.Reader, error) {\n", name)              //nolint:errcheck
			fmt.Fprintf(fi, "\tc := assets.New()\n")                                   //nolint:errcheck
			fmt.Fprintf(fi, "\tif err := c.FromBase64TGZ(__%s); err != nil {\n", name) //nolint:errcheck
			fmt.Fprintf(fi, "\t\treturn nil, err\n")                                   //nolint:errcheck
			fmt.Fprintf(fi, "\t}\n")                                                   //nolint:errcheck
			fmt.Fprintf(fi, "\treturn c, nil\n")                                       //nolint:errcheck
			fmt.Fprintf(fi, "}\n\n")                                                   //nolint:errcheck
			fmt.Fprintf(fi, "/* FILES:\n")                                             //nolint:errcheck
			fmt.Fprintf(fi, "%s\n", strings.Join(sf.List(), "\n"))                     //nolint:errcheck
			fmt.Fprintf(fi, "*/\n")                                                    //nolint:errcheck

		})
	})
}

func getPackageFromFirstFile(path string) (string, error) {
	list, err := fs.SearchFilesByExt(path, ".go")
	if err != nil {
		return "", err
	}

	for _, s := range list {
		if strings.Contains(s, assets.FileSuffix) {
			continue
		}
		if strings.Contains(s, "_test.go") {
			continue
		}

		b, err0 := os.ReadFile(s)
		if err0 != nil {
			return "", err0
		}

		result := packRex.FindAllStringSubmatch(string(b), -1)
		if len(result) == 1 && len(result[0]) == 2 {
			return result[0][1], nil
		}
	}

	return "", fmt.Errorf("empty folder")
}
