// Code generated by goppy-cli tb. DO NOT EDIT.
package client

import (
	context "context"

	jsonrpc "go.osspkg.com/goppy/v3/plugins/web/jsonrpc"
)

type UserClient struct {
	cli *jsonrpc.Client
}

func NewUserClient(address string, opts ...jsonrpc.Opt) *UserClient {
	return &UserClient{
		cli: jsonrpc.New(address, opts...),
	}
}

func (v *UserClient) CallNameV1(ctx context.Context, req UserNameV1Request) (res UserNameV1Response, err error) {
	err = v.cli.Call(ctx, req.Method(), req, &res)
	return
}
