// Code generated by goppy-cli tb. DO NOT EDIT.
package client

import (
	context "context"

	jsonrpc "go.osspkg.com/goppy/v3/plugins/web/jsonrpc"
)

type PostClient struct {
	cli *jsonrpc.Client
}

func NewPostClient(address string, opts ...jsonrpc.Opt) *PostClient {
	return &PostClient{
		cli: jsonrpc.New(address, opts...),
	}
}

func (v *PostClient) CallByID(ctx context.Context, req PostByIDRequest) (res PostByIDResponse, err error) {
	err = v.cli.Call(ctx, req.Method(), req, &res)
	return
}

func (v *PostClient) CallList(ctx context.Context, req PostListRequest) (res PostListResponse, err error) {
	err = v.cli.Call(ctx, req.Method(), req, &res)
	return
}
