// Code generated by goppy-cli tb. DO NOT EDIT.
package client

import (
	context "context"

	jsonrpc "go.osspkg.com/goppy/v3/plugins/web/jsonrpc"
)

type ApiClient struct {
	cli *jsonrpc.Client
}

func NewApiClient(address string, opts ...jsonrpc.Opt) *ApiClient {
	return &ApiClient{
		cli: jsonrpc.New(address, opts...),
	}
}

func (v *ApiClient) CallRootV1(ctx context.Context, req ApiRootV1Request) (res ApiRootV1Response, err error) {
	err = v.cli.Call(ctx, req.Method(), req, &res)
	return
}

func (v *ApiClient) CallAuthV1(ctx context.Context, req ApiAuthV1Request) (res ApiAuthV1Response, err error) {
	err = v.cli.Call(ctx, req.Method(), req, &res)
	return
}
