/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

package mod_json_rpc

import (
	"strings"

	. "go.osspkg.com/gogen/golang" //nolint:staticcheck
	"go.osspkg.com/gogen/types"
	"go.osspkg.com/syncing"

	at "go.osspkg.com/goppy/v3/apigen/types"
	"go.osspkg.com/goppy/v3/apigen/util"
)

func (v Module) buildTransport(w at.Writer, m at.GlobalMeta, files []at.File) error {

	t := Comment("Code generated by goppy-cli wsg. DO NOT EDIT.").
		Package(m.PkgName)

	list := syncing.NewMap[string, string](10)
	list.Set("context", "context")
	list.Set("strings", "strings")
	list.Set("errors", "errors")
	//list.Set("stdjson", "encoding/json")
	list.Set("syncing", "go.osspkg.com/syncing")
	list.Set("pool", "go.osspkg.com/ioutils/pool")
	list.Set("web", "go.osspkg.com/goppy/v3/web")
	list.Set("logx", "go.osspkg.com/logx")
	list.Set("time", "time")

	for _, file := range files {
		for _, object := range file.Faces {
			list.Set(object.Alias, object.Pkg)
			for alias, link := range file.Imports.Yield() {
				list.Set(alias, link)
			}
		}
	}

	for alias, link := range list.Yield() {
		t.Import(alias, link)
	}

	fields := []types.Token{
		ID("routes").Pkg("web").ID("ServerPool"),
	}
	fieldsInit := []types.Token{
		ID("routes").Op(":").ID("routes").Op(","),
	}
	for _, file := range files {
		for _, object := range file.Faces {
			fields = append(fields,
				ID("handle"+object.Name).Pkg(object.Alias).ID(object.Name),
			)
			fieldsInit = append(fieldsInit,
				ID("handle"+object.Name).Op(":").ID("handle"+object.Name).Op(","),
			)
		}
	}

	t = t.Join(
		Raw(`
var (
	poolBaseResponse = pool.New[*syncing.Slice[baseResponse]](func() *syncing.Slice[baseResponse] {
		return syncing.NewSlice[baseResponse](uint(2))
	})

	errUnsupportedMethod = errors.New("unsupported method")
)
`),
		Type().ID(transportName).Struct().Block(fields...),
		Line(),
		//-- New
		Func().ID("New"+transportName).Bracket(fields...).Op("*").ID(transportName).Block(
			Return().Op("&").ID(transportName).Block(fieldsInit...),
		),
		Line(),
		// -- Down
		Func().Bracket(ID("v").Op("*").ID(transportName)).
			ID("Down").Bracket().Error().Block(Return().Nil()),
		// -- Up
		Line(),
		Func().Bracket(ID("v").Op("*").ID(transportName)).
			ID("Up").Bracket(ID("ctx").Pkg("context").ID("Context")).Error().
			Block(v.buildUp(m, files)),
	)

	if err := w.WriteFile(v.FilePrefix+"_transport.go", t); err != nil {
		return err
	}

	return nil
}

func (v Module) buildUp(m at.GlobalMeta, files []at.File) types.Token {
	tokBase := ID("r").Op(".").ID("Post").Call(
		Text("/rpc"),
		Func().Bracket(ID("webCtx").Pkg("web").ID("Ctx")).Block(
			// ---
			Var().ID("req").ID(modelBulkBaseReq),
			If().
				ID("err").Op(":=").
				ID("webCtx").Op(".").ID("BindJSON").Bracket(Op("&").ID("req")).Op(";").
				ID("err").Op("!=").Nil().Block(
				ID("webCtx").Op(".").ID("String").Bracket(
					Raw("400"), ID("err").Op(".").ID("Error").Call(),
				),
				Return(),
			),
			// ---
			Line(),
			ID("res").Op(":=").ID("poolBaseResponse").Op(".").ID("Get").Call(),
			Defer().ID("poolBaseResponse").Op(".").ID("Put").Call(ID("res")),
			Line(),
			ID("wg").Op(":=").Pkg("syncing").ID("NewGroup").Bracket(
				ID("webCtx").Op(".").ID("Context").Call(),
			),
			ID("wg").Op(".").ID("OnPanic").Bracket(
				Func().Bracket(ID("err").Error()).Block(
					Pkg("logx").ID("Error").Call(
						Text("panic"), Text("err"), ID("err"),
					),
				),
			),
			// ---
			Line(),
			For().List(Raw("_"), ID("item")).Op(":=").Range().ID("req").Block(
				ID("item").Op(":=").ID("item"),
				v.buildMethods(files),
			),
			ID("wg").Op(".").ID("Wait").Call(),
			ID("webCtx").Op(".").ID("JSON").Bracket(
				Raw("200"), ID(modelBulkBaseRes).Bracket(
					ID("res").Op(".").ID("Extract").Bracket(),
				),
			),
		),
	)

	var poolTags []types.Token //nolint:prealloc
	for _, s := range m.Pool {
		poolTags = append(poolTags, Text(s))
	}

	return ID("v").Op(".").ID("routes").Op(".").ID("All").
		Bracket(
			Func().Bracket(ID("tag").String(), ID("r").Pkg("web").ID("Router")).Block(
				Switch().ID("tag").Block(
					Case().List(poolTags...).Op(":").Line().Join(tokBase),
				),
			),
		).
		Line().Return().Nil()
}

func (v Module) buildMethods(files []at.File) *Tokens {
	var list []types.Token

	for _, file := range files {
		for _, object := range file.Faces {
			for _, method := range object.Methods {
				methodName := strings.ToLower(object.Name + "." + method.Name)
				list = append(list,
					Case().Text(methodName).Op(":").Join(
						ID("wg").Op(".").ID("Background").Call(
							Text(methodName),
							Func().Bracket(ID("ctx").Pkg("context").ID("Context")).Block(
								ID("out").Op(":=").ID(modelBaseRes).Block(
									ID(util.ToUpperCamelCase(fieldID)).Op(":").
										ID("item").Op(".").ID(util.ToUpperCamelCase(fieldID)).Op(","),
								),

								Var().ID("err").Error(),
								Var().ID("result").Any(),
								List(ID("ctx"), ID("cancel")).Op(":=").Pkg("context").ID("WithTimeout").Call(ID(
									"ctx"), Raw("5").Op("*").Pkg("time").ID("Second")),
								Defer().ID("cancel").Call(),

								List(ID("result"), ID("err")).Op("=").
									ID("v").Op(".").ID("call"+object.Name+method.Name).
									Call(
										ID("ctx"),
										ID("webCtx"),
										ID("item").Op(".").ID(util.ToUpperCamelCase(fieldParams)),
									),

								If().ID("err").Op("!=").Nil().Block(
									ID("out").Op(".").ID(util.ToUpperCamelCase(fieldError)).Op("=").
										ID("toJSONRPCError").Bracket(ID("err")),
								).Else().Block(
									ID("out").Op(".").ID(util.ToUpperCamelCase(fieldResult)).Op("=").
										ID("result"),
								),
								ID("res").Op(".").ID("Append").Bracket(ID("out")),
							),
						),
					),
				)
			}
		}
	}

	list = append(list,
		Default().Op(":").Join(
			ID("out").Op(":=").ID(modelBaseRes).Block(
				ID(util.ToUpperCamelCase(fieldID)).Op(":").
					ID("item").Op(".").ID(util.ToUpperCamelCase(fieldID)).Op(","),
			),
			ID("err").Op(":=").ID("errUnsupportedMethod"),
			ID("out").Op(".").ID(util.ToUpperCamelCase(fieldError)).Op("=").
				ID("toJSONRPCError").Bracket(ID("err")),

			ID("res").Op(".").ID("Append").Bracket(ID("out")),
		),
	)

	return Switch().Pkg("strings").ID("ToLower").Bracket(
		ID("item").Op(".").ID(util.ToUpperCamelCase(fieldMethod)),
	).Block(list...)
}
