/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

package mod_json_rpc

import (
	"fmt"

	"go.osspkg.com/do"
	. "go.osspkg.com/gogen/golang" //nolint:staticcheck
	"go.osspkg.com/gogen/types"
	"go.osspkg.com/syncing"

	at "go.osspkg.com/goppy/v3/apigen/types"
	"go.osspkg.com/goppy/v3/apigen/util"
)

func (v Module) buildTransportModels(w at.Writer, m at.GlobalMeta, files []at.File) error {
	t := Comment("Code generated by goppy-cli wsg. DO NOT EDIT.").
		Package(m.PkgName).
		Comment("go:generate easyjson")

	list := syncing.NewMap[string, string](10)

	var models []types.Token
	for _, file := range files {
		models = append(models, v.buildTransportModel(list, file)...)
	}

	for alias, link := range list.Yield() {
		t.Import(alias, link)
	}

	if err := w.WriteFile(v.FilePrefix+"_model.go", t.Join(models...)); err != nil {
		return err
	}

	return nil
}

func (v Module) buildTransportModel(imp at.ImportSetter, file at.File) []types.Token {
	var models []types.Token

	for _, object := range file.Faces {
		for _, method := range object.Methods {

			args := map[string][]at.Param{
				modelNameReq: method.InParams,
				modelNameRes: method.OutParams,
			}

			for tmpl, params := range args {

				var (
					argsOut []types.Token
				)

				for _, p := range params {
					if ignoreModelParam(tmpl, p.Type, p.Pkg) {
						continue
					}

					if vals, ok := method.Tags[do.IfElse(tmpl == modelNameReq, "in.", "out.")+p.Name]; ok && noBodyParam(vals) {
						continue
					}

					if link, ok := file.Imports.Get(p.Pkg); ok {
						imp.Set(p.Pkg, link)
					}

					argsOut = append(argsOut,
						ID(util.ToUpperCamelCase(p.Name)).
							Raw(do.IfElse(p.Slice, "[]", "")).
							Raw(do.IfElse(p.Ptr, "*", "")).
							Pkg(p.Pkg).ID(p.Type).
							Raw(fmt.Sprintf("`json:\"%s%s\"`", p.Name,
								do.IfElse(p.Omitempty, ",omitempty", ""))),
					)
				}

				models = append(models, Line().Comment(jsonGenComment).
					Type().ID(fmt.Sprintf(tmpl, object.Name+method.Name)).Struct().Block(argsOut...),
				)
			}
		}
	}

	return models
}
