package mod_json_rpc

import (
	"fmt"

	. "go.osspkg.com/gogen/golang"
	at "go.osspkg.com/goppy/v3/apigen/types"
	"go.osspkg.com/goppy/v3/apigen/util"
)

func (v Module) buildBaseRPCModel(w at.Writer, m at.GlobalMeta) error {
	baseReq := Comment(jsonGenComment).
		Type().ID(modelBaseReq).Struct().
		Block(
			ID(util.ToUpperCamelCase(fieldID)).String().
				Raw(fmt.Sprintf("`json:\"%s\"`", fieldID)),
			ID(util.ToUpperCamelCase(fieldMethod)).String().
				Raw(fmt.Sprintf("`json:\"%s\"`", fieldMethod)),
			ID(util.ToUpperCamelCase(fieldParams)).Pkg("stdjson").ID("RawMessage").
				Raw(fmt.Sprintf("`json:\"%s\"`", fieldParams)),
		)

	bulkBaseReq := Comment(jsonGenComment).
		Type().ID(modelBulkBaseReq).Slice().ID(modelBaseReq)

	errRes := Comment(jsonGenComment).
		Type().ID(modelBaseErr).Struct().
		Block(
			ID(util.ToUpperCamelCase(fieldMessage)).String().
				Raw(fmt.Sprintf("`json:\"%s\"`", fieldMessage)),
			ID(util.ToUpperCamelCase(fieldCode)).Int64().
				Raw(fmt.Sprintf("`json:\"%s\"`", fieldCode)),
			ID(util.ToUpperCamelCase(fieldCtx)).Map(String(), String()).
				Raw(fmt.Sprintf("`json:\"%s,omitempty\"`", fieldCtx)),
		)

	errType := Type().ID(errInterface).Interface().
		Block(
			ID("GetCode").Bracket().Int64(),
			ID("GetMessage").Bracket().String(),
			ID("GetContext").Bracket().Map(String(), String()),
		)

	baseRes := Comment(jsonGenComment).
		Type().ID(modelBaseRes).Struct().
		Block(
			ID(util.ToUpperCamelCase(fieldID)).String().
				Raw(fmt.Sprintf("`json:\"%s\"`", fieldID)),
			ID(util.ToUpperCamelCase(fieldResult)).Any().
				Raw(fmt.Sprintf("`json:\"%s,omitempty\"`", fieldResult)),
			ID(util.ToUpperCamelCase(fieldError)).Op("*").ID("errResponse").
				Raw(fmt.Sprintf("`json:\"%s,omitempty\"`", fieldError)),
		)

	bulkBaseRes := Comment(jsonGenComment).
		Type().ID(modelBulkBaseRes).Slice().ID(modelBaseRes)

	toErr := Func().ID("toJSONRPCError").
		Bracket(ID("e").Error()).
		Bracket(Op("*").ID(modelBaseErr)).Block(
		If().ID("e").Op("==").Nil().Block(Return().Nil()),
		ID("err").Op(":=").Op("&").ID(modelBaseErr).Block(),
		List(ID("te"), ID("ok")).Op(":=").ID("e").Op(".").Bracket(ID(errInterface)),
		If().ID("ok").Block(
			ID("err").Op(".").ID("Code").Op("=").
				ID("te").Op(".").ID("GetCode").Bracket(),
			ID("err").Op(".").ID("Message").Op("=").
				ID("te").Op(".").ID("GetMessage").Bracket(),
			ID("err").Op(".").ID("Ctx").Op("=").
				ID("te").Op(".").ID("GetContext").Bracket(),
		).Else().Block(
			ID("err").Op(".").ID("Message").Op("=").
				ID("e").Op(".").ID("Error").Bracket(),
		),
		Return().ID("err"),
	)

	t := Comment("Code generated by goppy-cli wsg. DO NOT EDIT.").
		Package(m.PkgName).
		Comment("go:generate easyjson").
		Import("stdjson", "encoding/json").
		Join(baseReq, bulkBaseReq, baseRes, bulkBaseRes, errRes, errType, toErr)

	return w.WriteFile(v.FilePrefix+"_model_base.go", t)
}
