package mod_json_rpc

import (
	"fmt"

	"go.osspkg.com/do"
	. "go.osspkg.com/gogen/golang"
	"go.osspkg.com/gogen/types"
	at "go.osspkg.com/goppy/v3/apigen/types"
	"go.osspkg.com/goppy/v3/apigen/util"
	"go.osspkg.com/syncing"
)

func (v Module) buildTransportHandlers(w at.Writer, m at.GlobalMeta, files []at.File) error {
	t := Comment("Code generated by goppy-cli wsg. DO NOT EDIT.").
		Package(m.PkgName)

	list := syncing.NewMap[string, string](10)
	list.Set("context", "context")
	list.Set("stdjson", "encoding/json")
	list.Set("web", "go.osspkg.com/goppy/v3/web")

	var handlers []types.Token
	for _, file := range files {
		handlers = append(handlers, v.buildTransportHandler(list, file)...)
	}

	for alias, link := range list.Yield() {
		t.Import(alias, link)
	}

	if err := w.WriteFile(v.FilePrefix+"_handler.go", t.Join(handlers...)); err != nil {
		return err
	}

	return nil
}

func (v Module) buildTransportHandler(imp at.ImportSetter, file at.File) []types.Token {
	var models []types.Token

	for _, object := range file.Faces {
		for _, method := range object.Methods {
			handle := Func().Bracket(ID("v").Op("*").ID(transportName)).
				ID("call"+object.Name+method.Name).Bracket(
				ID("ctx").Pkg("context").ID("Context"),
				ID("webCtx").Pkg("web").ID("Ctx"),
				ID("param").Pkg("stdjson").ID("RawMessage"),
			).Bracket(
				Any(),
				Error(),
			)

			var handleSrc []types.Token

			handleSrc = append(handleSrc,
				Var().ID("req").ID(fmt.Sprintf(modelNameReq, object.Name+method.Name)),
				ID("err").Op(":=").Pkg("stdjson").ID("Unmarshal").Bracket(
					ID("param"), Op("&").ID("req"),
				),
				If().ID("err").Op("!=").Nil().Block(Return().List(Nil(), ID("err"))),
				Var().ID("res").ID(fmt.Sprintf(modelNameRes, object.Name+method.Name)),
			)

			// --------------------------------------

			inParamArgs := make(map[string]string)
			for _, p := range method.InParams {
				vals, ok := method.Tags["in."+p.Name]
				if !ok {
					continue
				}
				paramName := "in" + util.ToUpperCamelCase(p.Name)
				inParamArgs[p.Name] = paramName
				handleSrc = append(handleSrc,
					Var().ID(paramName).
						Raw(do.IfElse(p.Slice, "[]", "")).
						Raw(do.IfElse(p.Ptr, "*", "")).
						Pkg(p.Pkg).ID(p.Type),
				)
				for _, item := range vals {
					modName, modVal, modArgs := at.TagSplit(item)
					mod, ok := at.Resolve[at.ParamModule](modName)
					if !ok {
						continue
					}
					j := &at.Join{Tok: Comment("Module: " + mod.Name())}
					err := mod.Build(j, at.ParamMeta{
						Type:     at.ParamIn,
						CodeName: paramName,
						Import:   imp,
						Value:    modVal,
						Args:     modArgs,
					}, p)
					util.PanicIfError(err,
						"failed to build module %s: method: %s.%s, param: %s",
						modName, object.Name, method.Name, p.Name,
					)
					handleSrc = append(handleSrc, j.Tok)
				}
			}

			var (
				handleIn []types.Token
			)
			for _, p := range method.InParams {

				switch {
				case p.Pkg == "context" && p.Type == "Context":
					handleIn = append(handleIn, ID("ctx"))
				default:
					if name, ok := inParamArgs[p.Name]; ok {
						if link, ok := file.Imports.Get(p.Pkg); ok {
							imp.Set(p.Pkg, link)
						}

						handleIn = append(handleIn, ID(name))
					} else {
						handleIn = append(handleIn, ID("req").Op(".").ID(util.ToUpperCamelCase(p.Name)))
					}
				}
			}

			// --------------------------------------

			outParamArgs := make(map[string]string)
			for _, p := range method.OutParams {
				vals, ok := method.Tags["out."+p.Name]
				fmt.Println(vals, ok, p.Name)
				if !ok {
					continue
				}
				paramName := "out" + util.ToUpperCamelCase(p.Name)
				outParamArgs[p.Name] = paramName
				handleSrc = append(handleSrc,
					Var().ID(paramName).
						Raw(do.IfElse(p.Slice, "[]", "")).
						Raw(do.IfElse(p.Ptr, "*", "")).
						Pkg(p.Pkg).ID(p.Type),
				)
				for _, item := range vals {
					modName, modVal, modArgs := at.TagSplit(item)
					mod, ok := at.Resolve[at.ParamModule](modName)
					if !ok {
						continue
					}
					j := &at.Join{Tok: Comment("Module: " + mod.Name())}
					err := mod.Build(j, at.ParamMeta{
						Type:     at.ParamOut,
						CodeName: paramName,
						Import:   imp,
						Value:    modVal,
						Args:     modArgs,
					}, p)
					util.PanicIfError(err,
						"failed to build module %s: method: %s.%s, param: %s",
						modName, object.Name, method.Name, p.Name,
					)
					handleSrc = append(handleSrc,
						Defer().Func().Bracket().Block(j.Tok).Bracket(),
					)
				}
			}

			var (
				handleOut []types.Token
			)
			for _, p := range method.OutParams {

				switch {
				case p.Type == "error":
					handleOut = append(handleOut, ID("err"))
				default:
					if name, ok := outParamArgs[p.Name]; ok {
						if link, ok := file.Imports.Get(p.Pkg); ok {
							imp.Set(p.Pkg, link)
						}

						handleOut = append(handleOut, ID(name))
					} else {
						handleOut = append(handleOut, ID("res").Op(".").ID(util.ToUpperCamelCase(p.Name)))
					}
				}
			}

			// --------------------------------------

			handleSrc = append(handleSrc,
				List(handleOut...).Op("=").ID("v").Op(".").ID("handle"+object.Name).Op(".").ID(method.Name).Call(handleIn...),
				If().ID("err").Op("!=").Nil().Block(Return().List(Nil(), ID("err"))),
				Return().List(ID("res"), Nil()),
			)

			models = append(models, handle.Block(handleSrc...))
		}
	}

	return models
}
