/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

package mod_json_rpc

import (
	"fmt"
	"strings"

	"go.osspkg.com/do"
	. "go.osspkg.com/gogen/golang" //nolint:staticcheck
	"go.osspkg.com/gogen/types"
	"go.osspkg.com/syncing"

	at "go.osspkg.com/goppy/v3/apigen/types"
	"go.osspkg.com/goppy/v3/apigen/util"
)

func (v Module) buildTransportHandlers(w at.Writer, m at.GlobalMeta, files []at.File) error {
	for _, file := range files {
		for _, face := range file.Faces {
			t := Comment("Code generated by goppy-cli wsg. DO NOT EDIT.").
				Package(m.PkgName)

			list := syncing.NewMap[string, string](10)
			list.Set("context", "context")
			list.Set("fmt", "fmt")
			list.Set("stdjson", "encoding/json")
			list.Set("stdjson", "encoding/json")
			list.Set("web", "go.osspkg.com/goppy/v3/web")
			list.Set("jsonrpc", "go.osspkg.com/goppy/v3/web/jsonrpc")

			handlers := v.buildTransport(list, face)
			handlers = append(handlers, v.buildTransportHandler(list, file.Imports, face)...)

			for alias, link := range list.Yield() {
				t.Import(alias, link)
			}

			if err := w.WriteFile(v.FilePrefix+"_"+strings.ToLower(face.Name)+"_handler.go", t.Join(handlers...)); err != nil {
				return err
			}
		}
	}

	return nil
}

func (v Module) buildTransport(
	imp at.ImportSetter, object at.Face,
) (out []types.Token) {

	imp.Set(object.Alias, object.Pkg)

	fields := []types.Token{}
	fieldsInit := []types.Token{}

	fields = append(fields,
		ID("handle").Pkg(object.Alias).ID(object.Name),
		ID("tags").Slice().String(),
	)
	fieldsInit = append(fieldsInit,
		ID("handle").Op(":").ID("handle").Op(","),
		ID("tags").Op(":").ID("tags").Op(","),
	)

	trName := fmt.Sprintf(transportName, object.Name)

	out = append(out,
		Type().ID(trName).Struct().Block(fields...),
		Line(),
		//-- New
		Func().ID("New"+trName).Bracket(fields...).Op("*").ID(trName).Block(
			Return().Op("&").ID(trName).Block(fieldsInit...),
		),
		Line(),
		Func().Bracket(ID("v").Op("*").ID(trName)).
			ID("RouteTags").Bracket().Slice().String().
			Block(
				Return().ID("v").Op(".").ID("tags"),
			),
		Line(),
		Func().Bracket(ID("v").Op("*").ID(trName)).
			ID("JSONRPCApiHandlers").Bracket().Map(String(), Pkg("jsonrpc").ID("THandleFunc")).
			Block(
				Return().Map(String(), Pkg("jsonrpc").ID("THandleFunc")).Block(
					func() []types.Token {
						var models []types.Token
						for _, method := range object.Methods {
							models = append(models,
								Text(strings.ToLower(object.Name+"."+method.Name)).Op(":").
									ID("v").Op(".").ID("Call"+method.Name).Op(","),
							)
						}
						return models
					}()...,
				),
			),
		Line(),
	)

	return
}

func (v Module) buildTransportHandler(imp at.ImportSetter, imports *syncing.Map[string, string], object at.Face) []types.Token {
	var models []types.Token //nolint:prealloc

	trName := fmt.Sprintf(transportName, object.Name)

	for _, method := range object.Methods {
		handle := Func().Bracket(ID("v").Op("*").ID(trName)).
			ID("Call"+method.Name).Bracket(
			ID("ctx").Pkg("context").ID("Context"),
			ID("webCtx").Pkg("web").ID("Ctx"),
			ID("param").Pkg("stdjson").ID("RawMessage"),
		).Bracket(
			Any(),
			Error(),
		)

		var handleSrc []types.Token

		handleSrc = append(handleSrc,
			Var().ID("req").ID(fmt.Sprintf(modelNameReq, object.Name+method.Name)),
			ID("err").Op(":=").Pkg("stdjson").ID("Unmarshal").Bracket(
				ID("param"), Op("&").ID("req"),
			),
			If().ID("err").Op("!=").Nil().Block(
				ID("err").Op("=").Pkg("fmt").ID("Errorf").Bracket(
					Text("invalid request: %w"),
					ID("err"),
				),
				Return().List(
					Nil(),
					ID("err"),
				)),
			Var().ID("res").ID(fmt.Sprintf(modelNameRes, object.Name+method.Name)),
		)

		// --------------------------------------

		inParamArgs := make(map[string]string)
		for _, p := range method.InParams {
			vals, ok := method.Tags["in."+p.Name]
			if !ok {
				continue
			}
			paramName := "in" + util.ToUpperCamelCase(p.Name)
			inParamArgs[p.Name] = paramName
			handleSrc = append(handleSrc,
				Var().ID(paramName).
					Raw(do.IfElse(p.Slice, "[]", "")).
					Raw(do.IfElse(p.Ptr, "*", "")).
					Pkg(p.Pkg).ID(p.Type),
			)
			for _, item := range vals {
				modName, modVal, modArgs := at.TagSplit(item)
				mod, ok := at.Resolve[at.ParamModule](modName)
				if !ok {
					continue
				}
				j := &at.Join{Tok: Comment("Module: " + mod.Name())}
				err := mod.Build(j, at.ParamMeta{
					Type:     at.ParamIn,
					CodeName: paramName,
					Import:   imp,
					Value:    modVal,
					Args:     modArgs,
				}, p)
				util.PanicIfError(err,
					"failed to build module %s: method: %s.%s, param: %s",
					modName, object.Name, method.Name, p.Name,
				)
				handleSrc = append(handleSrc, j.Tok)
			}
		}

		var (
			handleIn []types.Token
		)
		for _, p := range method.InParams {

			switch {
			case p.Pkg == "context" && p.Type == "Context":
				handleIn = append(handleIn, ID("ctx"))
			default:
				if name, ok := inParamArgs[p.Name]; ok {
					if link, ok := imports.Get(p.Pkg); ok {
						imp.Set(p.Pkg, link)
					}

					handleIn = append(handleIn, ID(name))
				} else {
					handleIn = append(handleIn, ID("req").Op(".").ID(util.ToUpperCamelCase(p.Name)))
				}
			}
		}

		// --------------------------------------

		outParamArgs := make(map[string]string)
		for _, p := range method.OutParams {
			vals, ok := method.Tags["out."+p.Name]
			if !ok {
				continue
			}
			paramName := "out" + util.ToUpperCamelCase(p.Name)
			outParamArgs[p.Name] = paramName
			handleSrc = append(handleSrc,
				Var().ID(paramName).
					Raw(do.IfElse(p.Slice, "[]", "")).
					Raw(do.IfElse(p.Ptr, "*", "")).
					Pkg(p.Pkg).ID(p.Type),
			)
			for _, item := range vals {
				modName, modVal, modArgs := at.TagSplit(item)
				mod, ok := at.Resolve[at.ParamModule](modName)
				if !ok {
					continue
				}
				j := &at.Join{Tok: Comment("Module: " + mod.Name())}
				err := mod.Build(j, at.ParamMeta{
					Type:     at.ParamOut,
					CodeName: paramName,
					Import:   imp,
					Value:    modVal,
					Args:     modArgs,
				}, p)
				util.PanicIfError(err,
					"failed to build module %s: method: %s.%s, param: %s",
					modName, object.Name, method.Name, p.Name,
				)
				handleSrc = append(handleSrc,
					Defer().Func().Bracket().Block(j.Tok).Bracket(),
				)
			}
		}

		var (
			handleOut []types.Token
		)
		for _, p := range method.OutParams {

			switch { //nolint:staticcheck
			case p.Type == "error":
				handleOut = append(handleOut, ID("err"))
			default:
				if name, ok := outParamArgs[p.Name]; ok {
					if link, ok := imports.Get(p.Pkg); ok {
						imp.Set(p.Pkg, link)
					}

					handleOut = append(handleOut, ID(name))
				} else {
					handleOut = append(handleOut, ID("res").Op(".").ID(util.ToUpperCamelCase(p.Name)))
				}
			}
		}

		// --------------------------------------

		handleSrc = append(handleSrc,
			List(handleOut...).Op("=").ID("v").Op(".").ID("handle").Op(".").ID(method.Name).Call(handleIn...),
			If().ID("err").Op("!=").Nil().Block(
				Return().List(Nil(), ID("err")),
			),
			Return().List(ID("res"), Nil()),
		)

		models = append(models, handle.Block(handleSrc...))
	}

	return models
}
