package mod_json_rpc

import (
	"fmt"

	"go.osspkg.com/errors"
	. "go.osspkg.com/gogen/golang"
	at "go.osspkg.com/goppy/v3/apigen/types"
	"go.osspkg.com/goppy/v3/apigen/util"
)

type JSONRPCTransport struct {
	FilePrefix string
}

func (JSONRPCTransport) Name() string {
	return "json-rpc"
}

func (v JSONRPCTransport) Build(w at.Writer, m at.GlobalMeta, files []at.File) error {
	return errors.Queue(
		func() error { return v.buildBaseRPCModel(w, m) },
		//func() error { return v.buildTransport(ctx) },
		//func() error { return v.buildTransportModels(ctx) },
		//func() error { return v.buildTransportHandlers(ctx) },
	)
}

func (v JSONRPCTransport) buildBaseRPCModel(w at.Writer, m at.GlobalMeta) error {
	baseReq := Comment(jsonGenComment).
		Type().ID(modelBaseReq).Struct().
		Block(
			ID(util.ToUpperCamelCase(fieldID)).String().
				Raw(fmt.Sprintf("`json:\"%s\"`", fieldID)),
			ID(util.ToUpperCamelCase(fieldMethod)).String().
				Raw(fmt.Sprintf("`json:\"%s\"`", fieldMethod)),
			ID(util.ToUpperCamelCase(fieldParams)).Pkg("stdjson").ID("RawMessage").
				Raw(fmt.Sprintf("`json:\"%s\"`", fieldParams)),
		)

	bulkBaseReq := Comment(jsonGenComment).
		Type().ID(modelBulkBaseReq).Slice().ID(modelBaseReq)

	errRes := Comment(jsonGenComment).
		Type().ID(modelBaseErr).Struct().
		Block(
			ID(util.ToUpperCamelCase(fieldMessage)).String().
				Raw(fmt.Sprintf("`json:\"%s\"`", fieldMessage)),
			ID(util.ToUpperCamelCase(fieldCode)).Int64().
				Raw(fmt.Sprintf("`json:\"%s\"`", fieldCode)),
			ID(util.ToUpperCamelCase(fieldCtx)).Map(String(), String()).
				Raw(fmt.Sprintf("`json:\"%s,omitempty\"`", fieldCtx)),
		)

	errType := Type().ID(errInterface).Interface().
		Block(
			ID("GetCode").Bracket().Int64(),
			ID("GetMessage").Bracket().String(),
			ID("GetContext").Bracket().Map(String(), String()),
		)

	baseRes := Comment(jsonGenComment).
		Type().ID(modelBaseRes).Struct().
		Block(
			ID(util.ToUpperCamelCase(fieldID)).String().
				Raw(fmt.Sprintf("`json:\"%s\"`", fieldID)),
			ID(util.ToUpperCamelCase(fieldResult)).Any().
				Raw(fmt.Sprintf("`json:\"%s,omitempty\"`", fieldResult)),
			ID(util.ToUpperCamelCase(fieldError)).Op("*").ID("errResponse").
				Raw(fmt.Sprintf("`json:\"%s,omitempty\"`", fieldError)),
		)

	bulkBaseRes := Comment(jsonGenComment).
		Type().ID(modelBulkBaseRes).Slice().ID(modelBaseRes)

	toErr := Func().ID("toJSONRPCError").
		Bracket(ID("e").Error()).
		Bracket(Op("*").ID(modelBaseErr)).Block(
		If().ID("e").Op("==").Nil().Block(Return().Nil()),
		ID("err").Op(":=").Op("&").ID(modelBaseErr).Block(),
		List(ID("te"), ID("ok")).Op(":=").ID("e").Op(".").Bracket(ID(errInterface)),
		If().ID("ok").Block(
			ID("err").Op(".").ID("Code").Op("=").
				ID("te").Op(".").ID("GetCode").Bracket(),
			ID("err").Op(".").ID("Message").Op("=").
				ID("te").Op(".").ID("GetMessage").Bracket(),
			ID("err").Op(".").ID("Ctx").Op("=").
				ID("te").Op(".").ID("GetContext").Bracket(),
		).Else().Block(
			ID("err").Op(".").ID("Message").Op("=").
				ID("e").Op(".").ID("Error").Bracket(),
		),
		Return().ID("err"),
	)

	t := Comment("Code generated by goppy-cli wsg. DO NOT EDIT.").
		Package(m.PkgName).
		Comment("go:generate easyjson").
		Import("stdjson", "encoding/json").
		Join(baseReq, bulkBaseReq, baseRes, bulkBaseRes, errRes, errType, toErr)

	return w.WriteFile(v.FilePrefix+"_model.go", t)
}

//	func (v JSONRPCTransport) buildTransportModels(ctx at.Ctx) error {
//		t := Comment("Code generated by goppy-cli wsg. DO NOT EDIT.").
//			Package(ctx.PkgName).
//			Comment("go:generate easyjson")
//
//		list := syncing.NewMap[string, string](10)
//
//		var models []types.Token
//
//		for _, method := range ctx.Object.Methods {
//			var (
//				argsOut []types.Token
//			)
//			for _, p := range method.OutParams {
//				switch {
//				case p.Type == "error":
//					continue
//				default:
//				}
//
//				if link, ok := ctx.File.Imports.Get(p.Pkg); ok {
//					list.Set(p.Pkg, link)
//				}
//
//				argsOut = append(argsOut,
//					ID(util.ToUpperCamelCase(p.Name)).Pkg(p.Pkg).ID(p.Type).
//						Raw(fmt.Sprintf("`json:\"%s%s\"`", p.Name,
//							do.IfElse(p.Omitempty, ",omitempty", ""))),
//				)
//			}
//			models = append(models, Line().Comment(jsonGenComment).
//				Type().ID(fmt.Sprintf(modelNameRes, method.Name)).Struct().Block(argsOut...),
//			)
//
//			var (
//				argsIn []types.Token
//			)
//			for _, p := range method.InParams {
//				switch {
//				case p.Pkg == "context" && p.Type == "Context":
//					continue
//				default:
//				}
//
//				if link, ok := ctx.File.Imports.Get(p.Pkg); ok {
//					list.Set(p.Pkg, link)
//				}
//
//				argsIn = append(argsIn,
//					ID(util.ToUpperCamelCase(p.Name)).Pkg(p.Pkg).ID(p.Type).
//						Raw(fmt.Sprintf("`json:\"%s%s\"`", p.Name,
//							do.IfElse(p.Omitempty, ",omitempty", ""))),
//				)
//			}
//			models = append(models, Line().Comment(jsonGenComment).
//				Type().ID(fmt.Sprintf(modelNameReq, method.Name)).Struct().Block(argsIn...),
//			)
//		}
//
//		for alias, link := range list.Yield() {
//			t.Import(alias, link)
//		}
//
//		return ctx.W.WriteFile(v.FilePrefix+"_"+ctx.Object.Name+"_models.go", t.Join(models...))
//	}
//
//	func (v JSONRPCTransport) buildTransportHandlers(ctx at.Ctx) error {
//		objectName := fmt.Sprintf(transportName, ctx.Object.Name)
//
//		t := Comment("Code generated by goppy-cli wsg. DO NOT EDIT.").
//			Package(ctx.PkgName)
//
//		list := syncing.NewMap[string, string](10)
//		list.Set("context", "context")
//		list.Set("stdjson", "encoding/json")
//
//		var models []types.Token
//
//		for _, method := range ctx.Object.Methods {
//			handle := Func().Bracket(ID("v").Op("*").ID(objectName)).
//				ID("method"+method.Name).Bracket(
//				ID("ctx").Pkg("context").ID("Context"),
//				ID("param").Pkg("stdjson").ID("RawMessage"),
//			).Bracket(
//				Pkg("stdjson").ID("Marshaler"),
//				Error(),
//			)
//
//			var handleSrc []types.Token
//
//			handleSrc = append(handleSrc,
//				Var().ID("req").ID(fmt.Sprintf(modelNameReq, method.Name)),
//				ID("err").Op(":=").Pkg("stdjson").ID("Unmarshal").Bracket(
//					ID("param"), Op("&").ID("req"),
//				),
//				If().ID("err").Op("!=").Nil().Block(Return().List(Nil(), ID("err"))),
//				Var().ID("res").ID(fmt.Sprintf(modelNameRes, method.Name)),
//			)
//
//			var (
//				handleOut []types.Token
//			)
//			for _, p := range method.OutParams {
//				if link, ok := ctx.File.Imports.Get(p.Pkg); ok {
//					list.Set(p.Pkg, link)
//				}
//
//				switch {
//				case p.Type == "error":
//					handleOut = append(handleOut, ID("err"))
//				default:
//					handleOut = append(handleOut, ID("res").Op(".").ID(util.ToUpperCamelCase(p.Name)))
//				}
//			}
//
//			var (
//				handleIn []types.Token
//			)
//			for _, p := range method.InParams {
//				if link, ok := ctx.File.Imports.Get(p.Pkg); ok {
//					list.Set(p.Pkg, link)
//				}
//
//				switch {
//				case p.Pkg == "context" && p.Type == "Context":
//					handleIn = append(handleIn, ID("ctx"))
//				default:
//					handleIn = append(handleIn, ID("req").Op(".").ID(util.ToUpperCamelCase(p.Name)))
//				}
//			}
//
//			handleSrc = append(handleSrc,
//				List(handleOut...).Op("=").ID("v").Op(".").ID("handle").Op(".").ID(method.Name).Call(handleIn...),
//				If().ID("err").Op("!=").Nil().Block(Return().List(Nil(), ID("err"))),
//				Return().List(ID("res"), Nil()),
//			)
//
//			models = append(models, handle.Block(handleSrc...))
//		}
//
//		for alias, link := range list.Yield() {
//			t.Import(alias, link)
//		}
//
//		return ctx.W.WriteFile(v.FilePrefix+"_"+ctx.Object.Name+"_handlers.go", t.Join(models...))
//	}
//
//	func (v JSONRPCTransport) buildTransport(ctx at.Ctx) error {
//		objectName := fmt.Sprintf(transportName, ctx.Object.Name)
//
//		t := Comment("Code generated by goppy-cli wsg. DO NOT EDIT.").
//			Package(ctx.PkgName)
//
//		list := syncing.NewMap[string, string](10)
//		list.Set("context", "context")
//		list.Set("strings", "strings")
//		list.Set("errors", "errors")
//		list.Set("stdjson", "encoding/json")
//		list.Set("syncing", "go.osspkg.com/syncing")
//		list.Set("web", "go.osspkg.com/goppy/v3/web")
//		list.Set(ctx.Object.Alias, ctx.Object.Pkg)
//		for alias, link := range ctx.File.Imports.Yield() {
//			list.Set(alias, link)
//		}
//
//		for alias, link := range list.Yield() {
//			t.Import(alias, link)
//		}
//
//		t = t.Join(
//			Type().ID(objectName).Struct().Block(
//				ID("routes").Pkg("web").ID("ServerPool"),
//				ID("handle").Pkg(ctx.Object.Alias).ID(ctx.Object.Name),
//			),
//			//-- New
//			Func().ID("New"+objectName).Bracket(
//				ID("routes").Pkg("web").ID("ServerPool"),
//				ID("handle").Pkg(ctx.Object.Alias).ID(ctx.Object.Name),
//			).Op("*").ID(objectName).Block(
//				Return().Op("&").ID(objectName).Block(
//					ID("routes").Op(":").ID("routes").Op(","),
//					ID("handle").Op(":").ID("handle").Op(","),
//				),
//			),
//			// -- Down
//			Func().Bracket(ID("v").Op("*").ID(objectName)).
//				ID("Down").Bracket().Error().Block(Return().Nil()),
//			// -- Up
//			Func().Bracket(ID("v").Op("*").ID(objectName)).
//				ID("Up").Bracket(ID("ctx").Pkg("context").ID("Context")).Error().
//				Block(v.buildUp(ctx)),
//		)
//
//		return ctx.W.WriteFile(v.FilePrefix+"_"+ctx.Object.Name+"_transport.go", t)
//	}
//
//	func (v JSONRPCTransport) buildUp(ctx at.Ctx) *Tokens {
//		return ID("v").Op(".").ID("routes").Op(".").ID("All").Bracket(
//			Func().Bracket(ID("tag").String(), ID("r").Pkg("web").ID("Router")).Block(
//				func() *Tokens {
//					tags, ok := ctx.Tags[tagWebPool]
//					if !ok {
//						return Line()
//					}
//					var list []types.Token
//					for _, tag := range tags {
//						list = append(list, Text(tag))
//					}
//					return Switch().ID("tag").Block(
//						Case().List(list...).Op(":").Line().Join(
//							ID("r").Op(".").ID("Post").Call(
//								Text("/"+strings.ToLower(ctx.Object.Name)),
//								Func().Bracket(ID("ctx").Pkg("web").ID("Ctx")).Block(
//									Var().ID("req").ID(modelBulkBaseReq),
//									If().
//										ID("err").Op(":=").
//										ID("ctx").Op(".").ID("BindJSON").Bracket(Op("&").ID("req")).Op(";").
//										ID("err").Op("!=").Nil().Block(
//										ID("ctx").Op(".").ID("String").Bracket(
//											Raw("400"), ID("err").Op(".").ID("Error").Call(),
//										),
//										Return(),
//									),
//									ID("res").Op(":=").
//										Pkg("syncing").ID("NewSlice").Raw("[").ID(modelBaseRes).Raw("]").Call(
//										Uint().Bracket(Raw("len").Bracket(ID("req"))),
//									),
//									ID("wg").Op(":=").Pkg("syncing").ID("NewGroup").Bracket(
//										ID("ctx").Op(".").ID("Context").Call(),
//									),
//									For().List(Raw("_"), ID("item")).Op(":=").Range().ID("req").Block(
//										ID("item").Op(":=").ID("item"),
//
//										ID("wg").Op(".").ID("Background").Call(
//											Text(strings.ToLower(ctx.Object.Name)+".").Op("+").
//												Pkg("strings").ID("ToLower").Bracket(
//												ID("item").Op(".").ID(util.ToUpperCamelCase(fieldMethod)),
//											),
//											Func().Bracket(ID("ctx").Pkg("context").ID("Context")).Block(
//												ID("out").Op(":=").ID(modelBaseRes).Block(
//													ID(util.ToUpperCamelCase(fieldID)).Op(":").
//														ID("item").Op(".").ID(util.ToUpperCamelCase(fieldID)).Op(","),
//												),
//												Var().ID("err").Error(),
//												Var().ID("result").Pkg("stdjson").ID("Marshaler"),
//												v.buildMethods(ctx),
//												If().ID("err").Op("!=").Nil().Block(
//													ID("out").Op(".").ID(util.ToUpperCamelCase(fieldError)).Op("=").
//														ID("toJSONRPCError").Bracket(ID("err")),
//												).Else().Block(
//													ID("out").Op(".").ID(util.ToUpperCamelCase(fieldResult)).Op("=").
//														ID("result"),
//												),
//												ID("res").Op(".").ID("Append").Bracket(ID("out")),
//											),
//										),
//									),
//									ID("wg").Op(".").ID("Wait").Call(),
//									ID("ctx").Op(".").ID("JSON").Bracket(
//										Raw("200"), ID(modelBulkBaseRes).Bracket(
//											ID("res").Op(".").ID("Extract").Bracket(),
//										),
//									),
//								),
//							),
//						),
//					).Line().Return()
//				}(),
//			),
//		).
//			Line().Return().Nil()
//
// }
//func (v JSONRPCTransport) buildMethods(ctx at.Ctx) *Tokens {
//	var list []types.Token
//
//	for _, method := range ctx.Object.Methods {
//		list = append(list,
//			Case().Text(strings.ToLower(method.Name)).Op(":").Join(
//				List(ID("result"), ID("err")).Op("=").
//					ID("v").Op(".").ID("method"+method.Name).
//					Call(
//						ID("ctx"),
//						ID("item").Op(".").ID(util.ToUpperCamelCase(fieldParams)),
//					),
//			),
//		)
//	}
//
//	list = append(list,
//		Default().Op(":").Join(
//			ID("err").Op("=").Pkg("errors").ID("New").Bracket(Text("unsupported method")),
//		),
//	)
//
//	return Switch().Pkg("strings").ID("ToLower").Bracket(
//		ID("item").Op(".").ID(util.ToUpperCamelCase(fieldMethod)),
//	).Block(list...)
//}
