// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package oauth

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson40f907c5DecodeGoOsspkgComGoppyV3AuthOauth(in *jlexer.Lexer, out *modelGoogle) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "picture":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Icon = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "email_verified":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EmailVerified = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson40f907c5EncodeGoOsspkgComGoppyV3AuthOauth(out *jwriter.Writer, in modelGoogle) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"picture\":"
		out.RawString(prefix)
		out.String(string(in.Icon))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"email_verified\":"
		out.RawString(prefix)
		out.Bool(bool(in.EmailVerified))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v modelGoogle) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson40f907c5EncodeGoOsspkgComGoppyV3AuthOauth(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v modelGoogle) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson40f907c5EncodeGoOsspkgComGoppyV3AuthOauth(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *modelGoogle) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson40f907c5DecodeGoOsspkgComGoppyV3AuthOauth(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *modelGoogle) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson40f907c5DecodeGoOsspkgComGoppyV3AuthOauth(l, v)
}
