env: dev

log:
  file_path: /dev/stdout
  format: string
  level: 3

http:
  - tag: main
    addr: 0.0.0.0:10000

sqlite:
  - tags: sqlite_master
    file: ./sqlite.db
    cache: private
    mode: rwc
    journal: WAL
    locking_mode: EXCLUSIVE
    other_params: "auto_vacuum=incremental"

db_migrate:
  - tags: sqlite_master
    dialect: sqlite
    dir: ./migrations
