-- SEQUENCE
CREATE SEQUENCE IF NOT EXISTS "users__id__seq" INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

-- TABLE
CREATE TABLE IF NOT EXISTS "users"
(
	"id" BIGINT DEFAULT nextval('users__id__seq') NOT NULL,
	CONSTRAINT "users__id__pk" PRIMARY KEY ( "id" ),
	"name" VARCHAR( 100 ) NOT NULL,
	"value" TEXT[] NOT NULL,
	"meta0" JSONB NOT NULL
);

