/*
 *  Copyright (c) 2022-2025 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

// Code generated by goppy-cli for goppy.orm. DO NOT EDIT.
package go_gen

import (
	"fmt"
	"strings"

	"go.osspkg.com/ioutils/pool"
)

var _sqlBuilderPool = pool.New[*strings.Builder](func() *strings.Builder {
	return new(strings.Builder)
})

type ReadOption func(b *strings.Builder)

func Limit(arg uint64) ReadOption {
	return func(b *strings.Builder) {
		fmt.Fprintf(b, " LIMIT %d ", arg)
	}
}

type CreateOption func(b *strings.Builder)

func ConflictIgnore() CreateOption {
	return func(b *strings.Builder) {
		b.WriteString(" ON CONFLICT DO NOTHING ")
	}
}

func ConflictUpdate(fields []string, ups []string) CreateOption {
	return func(b *strings.Builder) {
		fmt.Fprintf(b, ` ON CONFLICT("%s") DO UPDATE SET `, strings.Join(fields, `","`))

		j := len(ups) - 1
		for i, up := range ups {
			fmt.Fprintf(b, `"%s" = EXCLUDED."%s"`, up, up)
			if i < j {
				b.WriteString(",")
			}
		}
	}
}
