/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

package mod_json_rpc_client

import (
	"fmt"
	"strings"

	. "go.osspkg.com/gogen/golang" //nolint:staticcheck
	"go.osspkg.com/gogen/types"
	"go.osspkg.com/syncing"

	at "go.osspkg.com/goppy/v3/pkg/apigen/types"
)

func (v Module) buildClientHandlers(w at.Writer, m at.GlobalMeta, files []at.File) error {
	for _, file := range files {
		for _, face := range file.Faces {
			t := Comment("Code generated by goppy-cli tb. DO NOT EDIT.").
				Package(m.PkgName)

			list := syncing.NewMap[string, string](10)
			list.Set("context", "context")
			list.Set("jsonrpc", "go.osspkg.com/goppy/v3/plugins/web/jsonrpc")

			handlers := v.buildClient(list, face)
			handlers = append(handlers, v.buildClientHandler(list, file.Imports, face)...)

			for alias, link := range list.Yield() {
				t.Import(alias, link)
			}

			if err := w.WriteFile(v.FilePrefix+"_"+strings.ToLower(face.Name)+"_handler.go", t.Join(handlers...)); err != nil {
				return err
			}
		}
	}

	return nil
}

func (v Module) buildClient(_ at.ImportSetter, object at.Face) (out []types.Token) {

	fields := []types.Token{}
	fieldsInit := []types.Token{}

	fields = append(fields,
		ID("cli").Op("*").Pkg("jsonrpc").ID("Client"),
	)
	fieldsInit = append(fieldsInit,
		ID("address").ID("string"),
		ID("opts").Op("...").Pkg("jsonrpc").ID("Opt"),
	)

	trName := fmt.Sprintf(clientName, object.Name)

	out = append(out,
		Type().ID(trName).Struct().Block(fields...),
		Line(),
		//-- New
		Func().ID("New"+trName).Bracket(fieldsInit...).Op("*").ID(trName).Block(
			Return().Op("&").ID(trName).Block(
				ID("cli").Op(":").Pkg("jsonrpc").ID("New").Bracket(
					ID("address"), ID("opts").Op("..."),
				).Op(","),
			),
		),
		Line(),
	)

	return
}

func (v Module) buildClientHandler(_ at.ImportSetter, _ *syncing.Map[string, string], object at.Face) []types.Token {
	var models []types.Token //nolint:prealloc

	trName := fmt.Sprintf(clientName, object.Name)

	for _, method := range object.Methods {
		handle := Func().Bracket(ID("v").Op("*").ID(trName)).
			ID("Call"+method.Name).Bracket(
			ID("ctx").Pkg("context").ID("Context"),
			ID("req").ID(fmt.Sprintf(modelNameRequest, object.Name+method.Name)),
		).Bracket(
			ID("res").ID(fmt.Sprintf(modelNameResponse, object.Name+method.Name)),
			ID("err").Error(),
		)

		var handleSrc []types.Token

		handleSrc = append(handleSrc,
			ID("err").Op("=").ID("v").Op(".").ID("cli").Op(".").ID("Call").Bracket(
				ID("ctx"),
				ID("req").Op(".").ID("Method").Bracket(),
				ID("req"),
				Op("&").ID("res"),
			),
			Return(),
		)

		models = append(models, handle.Block(handleSrc...), Line())
	}

	return models
}
