// Code generated by goppy-cli tb. DO NOT EDIT.
package transport

import (
	context "context"
	fmt "fmt"

	stdjson "encoding/json"

	jsonrpc "go.osspkg.com/goppy/v3/plugins/web/jsonrpc"

	web "go.osspkg.com/goppy/v3/plugins/web"

	types "go.osspkg.com/goppy/v3/examples/internal/transport-generate/types"
)

type JSONRPCUserTransport struct {
	handle types.User
	tags   []string
}

func NewJSONRPCUserTransport(handle types.User, tags []string) *JSONRPCUserTransport {
	return &JSONRPCUserTransport{
		handle: handle,
		tags:   tags,
	}
}

func (v *JSONRPCUserTransport) RouteTags() []string {
	return v.tags
}

func (v *JSONRPCUserTransport) JSONRPCApiHandlers() map[string]jsonrpc.THandleFunc {
	return map[string]jsonrpc.THandleFunc{
		"user.namev1": v.CallNameV1,
	}
}

func (v *JSONRPCUserTransport) CallNameV1(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcUserNameV1ModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcUserNameV1ModelResponse
	res.Name, err = v.handle.NameV1(ctx, req.UserID)
	if err != nil {
		return nil, err
	}
	return res, nil
}
