/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

// Code generated by goppy-cli tb. DO NOT EDIT.
package transport

import (
	stdjson "encoding/json"
	fmt "fmt"

	web "go.osspkg.com/goppy/v3/plugins/web"

	jsonrpc "go.osspkg.com/goppy/v3/plugins/web/jsonrpc"

	cast "go.osspkg.com/cast"

	nethttp "net/http"

	time "time"

	context "context"

	types "go.osspkg.com/goppy/v3/examples/internal/transport-generate/types"

	validate "go.osspkg.com/validate"
)

type JSONRPCApiTransport struct {
	handle types.Api
	tags   []string
}

func NewJSONRPCApiTransport(handle types.Api, tags []string) *JSONRPCApiTransport {
	return &JSONRPCApiTransport{
		handle: handle,
		tags:   tags,
	}
}

func (v *JSONRPCApiTransport) RouteTags() []string {
	return v.tags
}

func (v *JSONRPCApiTransport) JSONRPCApiHandlers() map[string]jsonrpc.THandleFunc {
	return map[string]jsonrpc.THandleFunc{
		"api.rootv1": v.CallRootV1,
		"api.authv1": v.CallAuthV1,
	}
}

func (v *JSONRPCApiTransport) CallRootV1(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcApiRootV1ModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcApiRootV1ModelResponse
	//Module: cookie
	req.userID, err = cast.StrTo[int64](webCtx.Cookie().Get("x-user-id"))
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}

	//Module: validate
	err = validate.Global().Validate(ctx, func(cb validate.Callback) {
		cb.Require("no-empty", req.userID)
	})
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}

	//Module: validate
	err = validate.Global().Validate(ctx, func(cb validate.Callback) {
		cb.Optional("no-empty", req.UserName)
		cb.Optional("123", req.UserName)
	})
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}

	res.Status, err = v.handle.RootV1(ctx, req.userID, req.UserName)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCApiTransport) CallAuthV1(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcApiAuthV1ModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcApiAuthV1ModelResponse
	//Module: header
	req.userID, err = cast.StrTo[int64](webCtx.Header().Get("x-user-id"))
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}

	defer func() {
		//Module: header
		if err != nil {
			return
		}
		webCtx.Header().Set("x-user-id", fmt.Sprintf("%v", res.status))

	}()
	defer func() {
		//Module: cookie
		if err != nil {
			return
		}
		webCtx.Cookie().Set(&nethttp.Cookie{
			Name:     "uid",
			Value:    fmt.Sprintf("%v", res.status),
			Path:     "/",
			Expires:  time.Now().Add(86400 * time.Second),
			Secure:   true,
			HttpOnly: true,
			SameSite: nethttp.SameSiteStrictMode,
		})

	}()
	defer func() {
		//Module: cookie
		if err != nil {
			return
		}
		webCtx.Cookie().Set(&nethttp.Cookie{
			Name:     "uid",
			Value:    fmt.Sprintf("%v", res.status),
			Path:     "/",
			Expires:  time.Now().Add(86400 * time.Second),
			Secure:   true,
			HttpOnly: true,
			SameSite: nethttp.SameSiteStrictMode,
		})

	}()
	res.status, err = v.handle.AuthV1(ctx, req.userID, req.UserName)
	if err != nil {
		return nil, err
	}
	return res, nil
}
