// Code generated by goppy-cli tb. DO NOT EDIT.
package transport

//go:generate easyjson
import types "go.osspkg.com/goppy/v3/examples/internal/transport-generate/types"

//easyjson:json
type jsonrpcApiRootV1ModelRequest struct {
	UserName string `json:"userName"`
}

//easyjson:json
type jsonrpcApiRootV1ModelResponse struct {
	Status bool `json:"status"`
}

//easyjson:json
type jsonrpcApiAuthV1ModelRequest struct {
	UserName string `json:"userName"`
}

//easyjson:json
type jsonrpcApiAuthV1ModelResponse struct{}

//easyjson:json
type jsonrpcUserNameV1ModelRequest struct {
	UserID int64 `json:"userID"`
}

//easyjson:json
type jsonrpcUserNameV1ModelResponse struct {
	Name string `json:"name"`
}

//easyjson:json
type jsonrpcPostByIDModelRequest struct {
	ID int64 `json:"ID"`
}

//easyjson:json
type jsonrpcPostByIDModelResponse struct {
	Text bool `json:"text"`
}

//easyjson:json
type jsonrpcPostListModelRequest struct {
	UserID int64 `json:"userID"`
}

//easyjson:json
type jsonrpcPostListModelResponse struct {
	Text []types.Text `json:"text,omitempty"`
}
