// Code generated by goppy assets. DO NOT EDIT.

package static_files_gen

import "go.osspkg.com/goppy/v3/pkg/assets"

const __getWebUI = "H4sIAAAAAAAA/+yTT4vbMBDFc/aneL21C7YmdruGkl3aZnNY+he2S+lpUeSJLOJIQSOHup++xBQKufRQskvBv8sTEswb8XjKsi9smJ0TIqK6rkclolOll9Wf83g/p6qmGeisW/2ml6TjjP7Z6/Rz/wnqIsMFsAz7ITrbJjw3L1BSWeYllZf46Latdh3e+0H/bPmAxU7HbS+X5fzNoH3DPwoTdtcF3nYdxgGCyMLxwE0xTr4XRtggtU4goY+GYULDcAIbDhw9N1gP0Hh3d4MqX3a6F0bnDHthpFYnGO2xZmxC7xs4j9QyPtwuV5/uVti4jo9GKsv22my1ZUjSyZmH44s8WPZZppQNry17jjoxbNjvB2gRToI8l2iuCuT5pvfmynL6xuv72+ypc3ksVO+UG3Ns0647j8ff+k/Vq5P+z2uqpv4/BotnN5+XX79/WeGY/3W2GGWhRnnq5SYmJiYmzsavAAAA//84+OayAAwAAA=="

func getWebUI() (assets.Reader, error) {
	c := assets.New()
	if err := c.FromBase64TGZ(__getWebUI); err != nil {
		return nil, err
	}
	return c, nil
}

/* FILES:
/gen.go
/ui/index.html
*/
