// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package transport

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"

	types "go.osspkg.com/goppy/v3/examples/internal/web-server-gen/types"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport(in *jlexer.Lexer, out *jsonrpcUserNameV1ModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport(out *jwriter.Writer, in jsonrpcUserNameV1ModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcUserNameV1ModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcUserNameV1ModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcUserNameV1ModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcUserNameV1ModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport(l, v)
}
func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport1(in *jlexer.Lexer, out *jsonrpcUserNameV1ModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport1(out *jwriter.Writer, in jsonrpcUserNameV1ModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcUserNameV1ModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcUserNameV1ModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcUserNameV1ModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcUserNameV1ModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport1(l, v)
}
func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport2(in *jlexer.Lexer, out *jsonrpcPostListModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
				out.Text = nil
			} else {
				in.Delim('[')
				if out.Text == nil {
					if !in.IsDelim(']') {
						out.Text = make([]types.Text, 0, 2)
					} else {
						out.Text = []types.Text{}
					}
				} else {
					out.Text = (out.Text)[:0]
				}
				for !in.IsDelim(']') {
					var v1 types.Text
					easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTypes(in, &v1)
					out.Text = append(out.Text, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport2(out *jwriter.Writer, in jsonrpcPostListModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Text) != 0 {
		const prefix string = ",\"text\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v2, v3 := range in.Text {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTypes(out, v3)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcPostListModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcPostListModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcPostListModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcPostListModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport2(l, v)
}
func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTypes(in *jlexer.Lexer, out *types.Text) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "Text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTypes(out *jwriter.Writer, in types.Text) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"Text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	out.RawByte('}')
}
func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport3(in *jlexer.Lexer, out *jsonrpcPostListModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport3(out *jwriter.Writer, in jsonrpcPostListModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcPostListModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcPostListModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcPostListModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcPostListModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport3(l, v)
}
func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport4(in *jlexer.Lexer, out *jsonrpcPostByIDModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport4(out *jwriter.Writer, in jsonrpcPostByIDModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Text))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcPostByIDModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcPostByIDModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcPostByIDModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcPostByIDModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport4(l, v)
}
func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport5(in *jlexer.Lexer, out *jsonrpcPostByIDModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport5(out *jwriter.Writer, in jsonrpcPostByIDModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcPostByIDModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcPostByIDModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcPostByIDModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcPostByIDModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport5(l, v)
}
func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport6(in *jlexer.Lexer, out *jsonrpcApiRootV1ModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport6(out *jwriter.Writer, in jsonrpcApiRootV1ModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcApiRootV1ModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcApiRootV1ModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcApiRootV1ModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcApiRootV1ModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport6(l, v)
}
func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport7(in *jlexer.Lexer, out *jsonrpcApiRootV1ModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport7(out *jwriter.Writer, in jsonrpcApiRootV1ModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userName\":"
		out.RawString(prefix[1:])
		out.String(string(in.UserName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcApiRootV1ModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcApiRootV1ModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcApiRootV1ModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcApiRootV1ModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport7(l, v)
}
func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport8(in *jlexer.Lexer, out *jsonrpcApiAuthV1ModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport8(out *jwriter.Writer, in jsonrpcApiAuthV1ModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcApiAuthV1ModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcApiAuthV1ModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcApiAuthV1ModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcApiAuthV1ModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport8(l, v)
}
func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport9(in *jlexer.Lexer, out *jsonrpcApiAuthV1ModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport9(out *jwriter.Writer, in jsonrpcApiAuthV1ModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userName\":"
		out.RawString(prefix[1:])
		out.String(string(in.UserName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcApiAuthV1ModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcApiAuthV1ModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcApiAuthV1ModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcApiAuthV1ModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalWebServerGenTransport9(l, v)
}
