// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package transport

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"

	types "go.osspkg.com/goppy/v3/_example/web-server-gen/types"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport(in *jlexer.Lexer, out *jsonrpcUserNameModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport(out *jwriter.Writer, in jsonrpcUserNameModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcUserNameModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcUserNameModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcUserNameModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcUserNameModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport(l, v)
}
func easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport1(in *jlexer.Lexer, out *jsonrpcUserNameModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport1(out *jwriter.Writer, in jsonrpcUserNameModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcUserNameModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcUserNameModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcUserNameModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcUserNameModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport1(l, v)
}
func easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport2(in *jlexer.Lexer, out *jsonrpcPostListModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
				out.Text = nil
			} else {
				in.Delim('[')
				if out.Text == nil {
					if !in.IsDelim(']') {
						out.Text = make([]types.Text, 0, 2)
					} else {
						out.Text = []types.Text{}
					}
				} else {
					out.Text = (out.Text)[:0]
				}
				for !in.IsDelim(']') {
					var v1 types.Text
					easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTypes(in, &v1)
					out.Text = append(out.Text, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport2(out *jwriter.Writer, in jsonrpcPostListModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Text) != 0 {
		const prefix string = ",\"text\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v2, v3 := range in.Text {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTypes(out, v3)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcPostListModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcPostListModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcPostListModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcPostListModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport2(l, v)
}
func easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTypes(in *jlexer.Lexer, out *types.Text) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "Text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTypes(out *jwriter.Writer, in types.Text) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"Text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	out.RawByte('}')
}
func easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport3(in *jlexer.Lexer, out *jsonrpcPostListModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport3(out *jwriter.Writer, in jsonrpcPostListModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcPostListModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcPostListModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcPostListModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcPostListModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport3(l, v)
}
func easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport4(in *jlexer.Lexer, out *jsonrpcPostByIDModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport4(out *jwriter.Writer, in jsonrpcPostByIDModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Text))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcPostByIDModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcPostByIDModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcPostByIDModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcPostByIDModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport4(l, v)
}
func easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport5(in *jlexer.Lexer, out *jsonrpcPostByIDModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport5(out *jwriter.Writer, in jsonrpcPostByIDModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcPostByIDModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcPostByIDModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcPostByIDModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcPostByIDModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport5(l, v)
}
func easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport6(in *jlexer.Lexer, out *jsonrpcApiRootModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport6(out *jwriter.Writer, in jsonrpcApiRootModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcApiRootModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcApiRootModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcApiRootModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcApiRootModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport6(l, v)
}
func easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport7(in *jlexer.Lexer, out *jsonrpcApiRootModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport7(out *jwriter.Writer, in jsonrpcApiRootModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userName\":"
		out.RawString(prefix[1:])
		out.String(string(in.UserName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcApiRootModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcApiRootModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcApiRootModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcApiRootModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport7(l, v)
}
func easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport8(in *jlexer.Lexer, out *jsonrpcApiAuthModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport8(out *jwriter.Writer, in jsonrpcApiAuthModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcApiAuthModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcApiAuthModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcApiAuthModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcApiAuthModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport8(l, v)
}
func easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport9(in *jlexer.Lexer, out *jsonrpcApiAuthModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport9(out *jwriter.Writer, in jsonrpcApiAuthModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userName\":"
		out.RawString(prefix[1:])
		out.String(string(in.UserName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcApiAuthModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcApiAuthModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE35df14fEncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcApiAuthModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcApiAuthModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE35df14fDecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport9(l, v)
}
