// Code generated by goppy-cli wsg. DO NOT EDIT.
package transport

//go:generate easyjson

//easyjson:json
type jsonrpcRootModelResponse struct {
	Status bool `json:"status"`
}

//easyjson:json
type jsonrpcRootModelRequest struct {
	UserID   int64  `json:"userID"`
	UserName string `json:"userName"`
}

//easyjson:json
type jsonrpcAuthModelResponse struct {
	Status bool `json:"status"`
}

//easyjson:json
type jsonrpcAuthModelRequest struct {
	UserID   int64  `json:"userID"`
	UserName string `json:"userName"`
}
