// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package transport

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6363947DecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport(in *jlexer.Lexer, out *jsonrpcRootModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6363947EncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport(out *jwriter.Writer, in jsonrpcRootModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcRootModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6363947EncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcRootModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6363947EncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcRootModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6363947DecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcRootModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6363947DecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport(l, v)
}
func easyjson6363947DecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport1(in *jlexer.Lexer, out *jsonrpcRootModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "userName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6363947EncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport1(out *jwriter.Writer, in jsonrpcRootModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"userName\":"
		out.RawString(prefix)
		out.String(string(in.UserName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcRootModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6363947EncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcRootModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6363947EncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcRootModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6363947DecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcRootModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6363947DecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport1(l, v)
}
func easyjson6363947DecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport2(in *jlexer.Lexer, out *jsonrpcAuthModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6363947EncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport2(out *jwriter.Writer, in jsonrpcAuthModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcAuthModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6363947EncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcAuthModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6363947EncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcAuthModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6363947DecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcAuthModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6363947DecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport2(l, v)
}
func easyjson6363947DecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport3(in *jlexer.Lexer, out *jsonrpcAuthModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "userName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserName = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6363947EncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport3(out *jwriter.Writer, in jsonrpcAuthModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"userName\":"
		out.RawString(prefix)
		out.String(string(in.UserName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcAuthModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6363947EncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcAuthModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6363947EncodeGoOsspkgComGoppyV3ExampleWebServerGenTransport3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcAuthModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6363947DecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcAuthModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6363947DecodeGoOsspkgComGoppyV3ExampleWebServerGenTransport3(l, v)
}
