// Code generated by goppy-cli wsg. DO NOT EDIT.
package transport

//go:generate easyjson
import stdjson "encoding/json"

//easyjson:json
type baseRequest struct {
	Id     string             `json:"id"`
	Method string             `json:"method"`
	Params stdjson.RawMessage `json:"params"`
}

//easyjson:json
type bulkRequest []baseRequest

//easyjson:json
type baseResponse struct {
	Id     string       `json:"id"`
	Result any          `json:"result,omitempty"`
	Error  *errResponse `json:"error,omitempty"`
}

//easyjson:json
type bulkResponse []baseResponse

//easyjson:json
type errResponse struct {
	Message string            `json:"message"`
	Code    int64             `json:"code"`
	Ctx     map[string]string `json:"ctx,omitempty"`
}
type TError interface {
	GetCode() int64
	GetMessage() string
	GetContext() map[string]string
}

func toJSONRPCError(e error) *errResponse {
	if e == nil {
		return nil
	}
	err := &errResponse{}
	te, ok := e.(TError)
	if ok {
		err.Code = te.GetCode()
		err.Message = te.GetMessage()
		err.Ctx = te.GetContext()
	} else {
		err.Message = e.Error()
	}
	return err
}
