// Code generated by goppy-cli wsg. DO NOT EDIT.
package transport

import context "context"
import errors "errors"
import stdjson "encoding/json"
import syncing "go.osspkg.com/syncing"
import time "time"
import types "go.osspkg.com/goppy/v3/_example/web-server-gen/types"
import strings "strings"
import pool "go.osspkg.com/ioutils/pool"
import web "go.osspkg.com/goppy/v3/web"
import logx "go.osspkg.com/logx"

var (
	poolBaseResponse = pool.New[*syncing.Slice[baseResponse]](func() *syncing.Slice[baseResponse] {
		return syncing.NewSlice[baseResponse](uint(2))
	})

	errUnsupportedMethod = errors.New("unsupported method")
)

type JSONRPCHandler struct {
	routes     web.ServerPool
	handleApi  types.Api
	handleUser types.User
	handlePost types.Post
}

func NewJSONRPCHandler(routes web.ServerPool, handleApi types.Api, handleUser types.User, handlePost types.Post) *JSONRPCHandler {
	return &JSONRPCHandler{
		routes:     routes,
		handleApi:  handleApi,
		handleUser: handleUser,
		handlePost: handlePost,
	}
}

func (v *JSONRPCHandler) Down() error {
	return nil
}

func (v *JSONRPCHandler) Up(ctx context.Context) error {
	v.routes.All(func(tag string, r web.Router) {
		switch tag {
		case "main", "admin":
			r.Post("/rpc", func(webCtx web.Ctx) {
				var req bulkRequest
				if err := webCtx.BindJSON(&req); err != nil {
					webCtx.String(400, err.Error())
					return
				}

				res := poolBaseResponse.Get()
				defer poolBaseResponse.Put(res)

				wg := syncing.NewGroup(webCtx.Context())
				wg.OnPanic(func(err error) {
					logx.Error("panic", "err", err)
				})

				for _, item := range req {
					item := item
					switch strings.ToLower(item.Method) {
					case "api.root":
						wg.Background("api.root", func(ctx context.Context) {
							out := baseResponse{
								Id: item.Id,
							}
							var err error
							var result stdjson.Marshaler
							ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
							defer cancel()
							result, err = v.callApiRoot(ctx, webCtx, item.Params)
							if err != nil {
								out.Error = toJSONRPCError(err)
							} else {
								out.Result = result
							}
							res.Append(out)
						})

					case "api.auth":
						wg.Background("api.auth", func(ctx context.Context) {
							out := baseResponse{
								Id: item.Id,
							}
							var err error
							var result stdjson.Marshaler
							ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
							defer cancel()
							result, err = v.callApiAuth(ctx, webCtx, item.Params)
							if err != nil {
								out.Error = toJSONRPCError(err)
							} else {
								out.Result = result
							}
							res.Append(out)
						})

					case "user.name":
						wg.Background("user.name", func(ctx context.Context) {
							out := baseResponse{
								Id: item.Id,
							}
							var err error
							var result stdjson.Marshaler
							ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
							defer cancel()
							result, err = v.callUserName(ctx, webCtx, item.Params)
							if err != nil {
								out.Error = toJSONRPCError(err)
							} else {
								out.Result = result
							}
							res.Append(out)
						})

					case "post.byid":
						wg.Background("post.byid", func(ctx context.Context) {
							out := baseResponse{
								Id: item.Id,
							}
							var err error
							var result stdjson.Marshaler
							ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
							defer cancel()
							result, err = v.callPostByID(ctx, webCtx, item.Params)
							if err != nil {
								out.Error = toJSONRPCError(err)
							} else {
								out.Result = result
							}
							res.Append(out)
						})

					case "post.list":
						wg.Background("post.list", func(ctx context.Context) {
							out := baseResponse{
								Id: item.Id,
							}
							var err error
							var result stdjson.Marshaler
							ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
							defer cancel()
							result, err = v.callPostList(ctx, webCtx, item.Params)
							if err != nil {
								out.Error = toJSONRPCError(err)
							} else {
								out.Result = result
							}
							res.Append(out)
						})

					default:
						out := baseResponse{
							Id: item.Id,
						}
						err := errUnsupportedMethod
						out.Error = toJSONRPCError(err)
						res.Append(out)

					}
				}
				wg.Wait()
				ctx.JSON(200, bulkResponse(res.Extract()))
			})

		}
	})
	return nil
}
