/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

// Code generated by goppy-cli wsg. DO NOT EDIT.
package transport

import (
	context "context"
	time "time"

	fmt "fmt"

	web "go.osspkg.com/goppy/v3/web"

	jsonrpc "go.osspkg.com/goppy/v3/web/jsonrpc"

	nethttp "net/http"

	stdjson "encoding/json"

	types "go.osspkg.com/goppy/v3/_example/web-server-gen/types"
)

type JSONRPCApiTransport struct {
	handle types.Api
	tags   []string
}

func NewJSONRPCApiTransport(handle types.Api, tags []string) *JSONRPCApiTransport {
	return &JSONRPCApiTransport{
		handle: handle,
		tags:   tags,
	}
}

func (v *JSONRPCApiTransport) RouteTags() []string {
	return v.tags
}

func (v *JSONRPCApiTransport) JSONRPCApiHandlers() map[string]jsonrpc.THandleFunc {
	return map[string]jsonrpc.THandleFunc{
		"api.root": v.CallRoot,
		"api.auth": v.CallAuth,
	}
}

func (v *JSONRPCApiTransport) CallRoot(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcApiRootModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcApiRootModelResponse
	var inUserID int64
	//Module: cookie
	inUserID, _ = web.StrTo[int64](webCtx.Cookie().Get("x-user-id"))
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}

	res.Status, err = v.handle.Root(ctx, inUserID, req.UserName)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCApiTransport) CallAuth(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcApiAuthModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcApiAuthModelResponse
	var inUserID int64
	//Module: header
	inUserID, _ = web.StrTo[int64](webCtx.Header().Get("x-user-id"))
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}

	var outStatus bool
	defer func() {
		//Module: header
		if err != nil {
			return
		}
		webCtx.Header().Set("x-user-id", fmt.Sprintf("%v", outStatus))

	}()
	defer func() {
		//Module: cookie
		if err != nil {
			return
		}
		webCtx.Cookie().Set(&nethttp.Cookie{
			Name:     "uid",
			Value:    fmt.Sprintf("%v", outStatus),
			Path:     "/",
			Expires:  time.Now().Add(86400 * time.Second),
			Secure:   true,
			HttpOnly: true,
			SameSite: nethttp.SameSiteStrictMode,
		})

	}()
	defer func() {
		//Module: cookie
		if err != nil {
			return
		}
		webCtx.Cookie().Set(&nethttp.Cookie{
			Name:     "uid",
			Value:    fmt.Sprintf("%v", outStatus),
			Path:     "/",
			Expires:  time.Now().Add(86400 * time.Second),
			Secure:   true,
			HttpOnly: true,
			SameSite: nethttp.SameSiteStrictMode,
		})

	}()
	outStatus, err = v.handle.Auth(ctx, inUserID, req.UserName)
	if err != nil {
		return nil, err
	}
	return res, nil
}
