// Code generated by goppy-cli wsg. DO NOT EDIT.
package transport

import syncing "go.osspkg.com/syncing"
import web "go.osspkg.com/goppy/v3/web"
import types "go.osspkg.com/goppy/v3/_example/web-server-gen/types"
import context "context"
import strings "strings"
import errors "errors"
import stdjson "encoding/json"

type JSONRPCApiHandle struct {
	routes web.ServerPool
	handle types.Api
}

func NewJSONRPCApiHandle(routes web.ServerPool, handle types.Api) *JSONRPCApiHandle {
	return &JSONRPCApiHandle{
		routes: routes,
		handle: handle,
	}
}
func (v *JSONRPCApiHandle) Down() error {
	return nil
}
func (v *JSONRPCApiHandle) Up(ctx context.Context) error {
	v.routes.All(func(tag string, r web.Router) {
		switch tag {
		case "main", "admin":
			r.Post("/api", func(ctx web.Ctx) {
				var req bulkRequest
				if err := ctx.BindJSON(&req); err != nil {
					ctx.String(400, err.Error())
					return
				}
				res := syncing.NewSlice[baseResponse](uint(len(req)))
				wg := syncing.NewGroup(ctx.Context())
				for _, item := range req {
					item := item
					wg.Background("api."+strings.ToLower(item.Method), func(ctx context.Context) {
						out := baseResponse{
							Id: item.Id,
						}
						var err error
						var result stdjson.Marshaler
						switch strings.ToLower(item.Method) {
						case "root":
							result, err = v.methodRoot(ctx, item.Params)

						case "auth":
							result, err = v.methodAuth(ctx, item.Params)

						default:
							err = errors.New("unsupported method")

						}
						if err != nil {
							out.Error = toJSONRPCError(err)
						} else {
							out.Result = result
						}
						res.Append(out)
					})
				}
				wg.Wait()
				ctx.JSON(200, bulkResponse(res.Extract()))
			})

		}
		return
	})
	return nil
}
