/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

// Code generated by goppy-cli wsg. DO NOT EDIT.
package transport

//go:generate easyjson
import types "go.osspkg.com/goppy/v3/_example/web-server-gen/types"

//easyjson:json
type jsonrpcApiRootModelRequest struct {
	UserName string `json:"userName"`
}

//easyjson:json
type jsonrpcApiRootModelResponse struct {
	Status bool `json:"status"`
}

//easyjson:json
type jsonrpcApiAuthModelRequest struct {
	UserName string `json:"userName"`
}

//easyjson:json
type jsonrpcApiAuthModelResponse struct{}

//easyjson:json
type jsonrpcUserNameModelRequest struct {
	UserID int64 `json:"userID"`
}

//easyjson:json
type jsonrpcUserNameModelResponse struct {
	Name string `json:"name"`
}

//easyjson:json
type jsonrpcPostByIDModelRequest struct {
	ID int64 `json:"ID"`
}

//easyjson:json
type jsonrpcPostByIDModelResponse struct {
	Text bool `json:"text"`
}

//easyjson:json
type jsonrpcPostListModelRequest struct {
	UserID int64 `json:"userID"`
}

//easyjson:json
type jsonrpcPostListModelResponse struct {
	Text []types.Text `json:"text,omitempty"`
}
