// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  transport

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( jsonrpcAuthModelRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* jsonrpcAuthModelRequest ) UnmarshalJSON([]byte) error { return nil }
func ( jsonrpcAuthModelRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* jsonrpcAuthModelRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_jsonrpcAuthModelRequest *jsonrpcAuthModelRequest

func ( jsonrpcAuthModelResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* jsonrpcAuthModelResponse ) UnmarshalJSON([]byte) error { return nil }
func ( jsonrpcAuthModelResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* jsonrpcAuthModelResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_jsonrpcAuthModelResponse *jsonrpcAuthModelResponse

func ( jsonrpcRootModelRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* jsonrpcRootModelRequest ) UnmarshalJSON([]byte) error { return nil }
func ( jsonrpcRootModelRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* jsonrpcRootModelRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_jsonrpcRootModelRequest *jsonrpcRootModelRequest

func ( jsonrpcRootModelResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* jsonrpcRootModelResponse ) UnmarshalJSON([]byte) error { return nil }
func ( jsonrpcRootModelResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* jsonrpcRootModelResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_jsonrpcRootModelResponse *jsonrpcRootModelResponse
