// Code generated by goppy-cli wsg. DO NOT EDIT.
package transport

import context "context"
import stdjson "encoding/json"
import web "go.osspkg.com/goppy/v3/web"
import fmt "fmt"

func (v *JSONRPCHandler) callApiRoot(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcApiRootModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		return nil, err
	}
	var res jsonrpcApiRootModelResponse
	var inUserID int64
	//Module: cookie
	inUserID, _ = web.StrTo[int64](webCtx.Cookie().Get("x-user-id"))

	res.Status, err = v.handleApi.Root(ctx, inUserID, req.UserName)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCHandler) callApiAuth(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcApiAuthModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		return nil, err
	}
	var res jsonrpcApiAuthModelResponse
	var inUserID int64
	//Module: header
	inUserID, _ = web.StrTo[int64](webCtx.Header().Get("x-user-id"))

	var outStatus bool
	defer func() {
		//Module: header
		if err != nil {
			return
		}
		webCtx.Header().Set("x-user-id", fmt.Sprintf("%v", outStatus))

	}()
	outStatus, err = v.handleApi.Auth(ctx, inUserID, req.UserName)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCHandler) callUserName(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcUserNameModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		return nil, err
	}
	var res jsonrpcUserNameModelResponse
	res.Name, err = v.handleUser.Name(ctx, req.UserID)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCHandler) callPostByID(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcPostByIDModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		return nil, err
	}
	var res jsonrpcPostByIDModelResponse
	res.Text, err = v.handlePost.ByID(ctx, req.ID)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCHandler) callPostList(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcPostListModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		return nil, err
	}
	var res jsonrpcPostListModelResponse
	res.Text, err = v.handlePost.List(ctx, req.UserID)
	if err != nil {
		return nil, err
	}
	return res, nil
}
