/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

// Code generated by goppy-cli wsg. DO NOT EDIT.
package transport

import (
	context "context"
	stdjson "encoding/json"

	types "go.osspkg.com/goppy/v3/_example/web-server-gen/types"

	fmt "fmt"

	web "go.osspkg.com/goppy/v3/web"

	jsonrpc "go.osspkg.com/goppy/v3/web/jsonrpc"
)

type JSONRPCPostTransport struct {
	handle types.Post
	tags   []string
}

func NewJSONRPCPostTransport(handle types.Post, tags []string) *JSONRPCPostTransport {
	return &JSONRPCPostTransport{
		handle: handle,
		tags:   tags,
	}
}

func (v *JSONRPCPostTransport) RouteTags() []string {
	return v.tags
}

func (v *JSONRPCPostTransport) JSONRPCApiHandlers() map[string]jsonrpc.THandleFunc {
	return map[string]jsonrpc.THandleFunc{
		"post.byid": v.CallByID,
		"post.list": v.CallList,
	}
}

func (v *JSONRPCPostTransport) CallByID(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcPostByIDModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcPostByIDModelResponse
	res.Text, err = v.handle.ByID(ctx, req.ID)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCPostTransport) CallList(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcPostListModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcPostListModelResponse
	res.Text, err = v.handle.List(ctx, req.UserID)
	if err != nil {
		return nil, err
	}
	return res, nil
}
