// Code generated by goppy-cli wsg. DO NOT EDIT.
package transport

import context "context"
import stdjson "encoding/json"

func (v *JSONRPCApiHandle) methodRoot(ctx context.Context, param stdjson.RawMessage) (stdjson.Marshaler, error) {
	var req jsonrpcRootModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		return nil, err
	}
	var res jsonrpcRootModelResponse
	res.Status, err = v.handle.Root(ctx, req.UserID, req.UserName)
	if err != nil {
		return nil, err
	}
	return res, nil
}
func (v *JSONRPCApiHandle) methodAuth(ctx context.Context, param stdjson.RawMessage) (stdjson.Marshaler, error) {
	var req jsonrpcAuthModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		return nil, err
	}
	var res jsonrpcAuthModelResponse
	res.Status, err = v.handle.Auth(ctx, req.UserID, req.UserName)
	if err != nil {
		return nil, err
	}
	return res, nil
}
