/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

// Code generated by goppy-cli tb. DO NOT EDIT.
package transport

import (
	context "context"
	stdjson "encoding/json"

	jsonrpc "go.osspkg.com/goppy/v3/plugins/web/jsonrpc"

	fmt "fmt"

	web "go.osspkg.com/goppy/v3/plugins/web"

	types "go.osspkg.com/goppy/v3/examples/internal/rpc-app/rpc-unix-plugin/types"
)

type JSONRPCApiTransport struct {
	handle types.Api
	tags   []string
}

func NewJSONRPCApiTransport(handle types.Api, tags []string) *JSONRPCApiTransport {
	return &JSONRPCApiTransport{
		handle: handle,
		tags:   tags,
	}
}

func (v *JSONRPCApiTransport) RouteTags() []string {
	return v.tags
}

func (v *JSONRPCApiTransport) JSONRPCApiHandlers() map[string]jsonrpc.THandleFunc {
	return map[string]jsonrpc.THandleFunc{
		"api.ping": v.CallPing,
	}
}

func (v *JSONRPCApiTransport) CallPing(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcApiPingModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcApiPingModelResponse
	res.Pong, err = v.handle.Ping(ctx)
	if err != nil {
		return nil, err
	}
	return res, nil
}
