// Code generated by goppy-cli tb. DO NOT EDIT.
package transport

import (
	stdjson "encoding/json"

	web "go.osspkg.com/goppy/v3/plugins/web"
	jsonrpc "go.osspkg.com/goppy/v3/plugins/web/jsonrpc"

	context "context"

	fmt "fmt"

	types "go.osspkg.com/goppy/v3/examples/internal/rpc-app/rpc-unix-plugin/types"
)

type JSONRPCApiTransport struct {
	handle types.Api
	tags   []string
}

func NewJSONRPCApiTransport(handle types.Api, tags []string) *JSONRPCApiTransport {
	return &JSONRPCApiTransport{
		handle: handle,
		tags:   tags,
	}
}

func (v *JSONRPCApiTransport) RouteTags() []string {
	return v.tags
}

func (v *JSONRPCApiTransport) JSONRPCApiHandlers() map[string]jsonrpc.THandleFunc {
	return map[string]jsonrpc.THandleFunc{
		"api.ping": v.CallPing,
	}
}

func (v *JSONRPCApiTransport) CallPing(ctx context.Context, webCtx web.Ctx, param stdjson.RawMessage) (any, error) {
	var req jsonrpcApiPingModelRequest
	err := stdjson.Unmarshal(param, &req)
	if err != nil {
		err = fmt.Errorf("invalid request: %w", err)
		return nil, err
	}
	var res jsonrpcApiPingModelResponse
	res.Pong, err = v.handle.Ping(ctx)
	if err != nil {
		return nil, err
	}
	return res, nil
}
