// Code generated by goppy-cli tb. DO NOT EDIT.
package transport

//go:generate easyjson

//easyjson:json
type jsonrpcApiPingModelRequest struct{}

//easyjson:json
type jsonrpcApiPingModelResponse struct {
	Pong bool `json:"pong"`
}
