/*
 *  Copyright (c) 2022-2026 Mikhail Knyazhev <markus621@yandex.com>. All rights reserved.
 *  Use of this source code is governed by a BSD 3-Clause license that can be found in the LICENSE file.
 */

// Code generated by goppy-cli tb. DO NOT EDIT.
package transport

//go:generate easyjson

//easyjson:json
type jsonrpcApiPingModelRequest struct{}

//easyjson:json
type jsonrpcApiPingModelResponse struct {
	Pong bool `json:"pong"`
}
