// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package transport

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalRpcAppRpcUnixPluginTransport(in *jlexer.Lexer, out *jsonrpcApiPingModelResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "pong":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Pong = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalRpcAppRpcUnixPluginTransport(out *jwriter.Writer, in jsonrpcApiPingModelResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"pong\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Pong))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcApiPingModelResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalRpcAppRpcUnixPluginTransport(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcApiPingModelResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalRpcAppRpcUnixPluginTransport(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcApiPingModelResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalRpcAppRpcUnixPluginTransport(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcApiPingModelResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalRpcAppRpcUnixPluginTransport(l, v)
}
func easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalRpcAppRpcUnixPluginTransport1(in *jlexer.Lexer, out *jsonrpcApiPingModelRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalRpcAppRpcUnixPluginTransport1(out *jwriter.Writer, in jsonrpcApiPingModelRequest) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v jsonrpcApiPingModelRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalRpcAppRpcUnixPluginTransport1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v jsonrpcApiPingModelRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3ef10231EncodeGoOsspkgComGoppyV3ExamplesInternalRpcAppRpcUnixPluginTransport1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *jsonrpcApiPingModelRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalRpcAppRpcUnixPluginTransport1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *jsonrpcApiPingModelRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3ef10231DecodeGoOsspkgComGoppyV3ExamplesInternalRpcAppRpcUnixPluginTransport1(l, v)
}
